name: TP-GWAS
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab=2
  - nbresuse
  - python>=3.7
  - nodejs
  - pip
  - plink=1.90b6.12
  - king=2.2.4
  - r-base=4
  - r-qqman==0.1.4
  - pip:
    - bash_kernel
